### ISSUE TITLE
Simplifying this library

### ISSUE THREAD

**Issue by manuelbernhardt** [vmunier/play-scalajs-scripts#5]
This is more of a suggestion than an issue, it's about making the maintenance of this side-library easier. Rather than creating Twirl templates for providing the "automatically generate the scripts" functions, what about coding them in Scala (see an example [here](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/views/helper/Helpers.scala))? You'd basically not need the dependency on `PlayScala` anymore, and have the whole functionality in one Scala source file.

And going a little further, I would even advocate to provide this functionality directly as part of the [sbt-play-scalajs](https://github.com/vmunier/sbt-play-scalajs) plugin rather than a separate library, because that makes it easier on the user (no need to integrate another library, upgrade the version, etc.).

What do you think?

**Comment by vmunier** [comment]
Hi,

Have a look at the comment in build.sbt https://github.com/vmunier/play-scalajs-scripts/blob/master/build.sbt#L13-L14.
PlayScala is needed to call `Play.isProd(Play.current)` in `selectScript.scala.html`.

`sbt-play-scalajs` and `play-scalajs-scripts` are independent of one another.
People might care about the plugin settings but may not use the scripts.
Including the functionalities into the sbt plugin would force us to publish a new version every time the scripts are updated.

**Comment by manuelbernhardt** [comment]
Ah yes, I missed the dependency on `Play.current`. Well, that one may go away with Play 2.4 - but I suppose you'd still need to get a hold on some kind of context to know whether you're running in `PROD` or not.

Are you planning on adding many scripts? I was under the impression that the main purpose of this project was to hold the helpers to easily import the generated JS into Twirl templates, which I believe would be a very welcome feature by any user of the Play integration plugin. Anyway, it was just an idea to reduce the dependency count in a greenfield project using the plugins - I'm cooking together an example application for [this](http://manning.com/bernhardt) so I'm always looking at getting the simplest thing that could possibly work. Great work btw, I think this is going to be very useful to the whole Play / Scala ecosystem!
